### ISSUE TITLE
Proposal: DAL to abstract different backends

### ISSUE THREAD

**Issue by nerdondon** [siege918/siegebot-lfg-2.0#28]
As "discussed" (talked about b/w warzone lol) here is a proposal for a simple data access layer to abstract the persistence mechanisms that the bot uses.

The proposal is to bring back elements of the class based GroupCache from v1 and to add a generic service interface that can be implemented by an in-memory persistence mechanism or the DDB stack that was created. This allows for better testability and simpler local development.

This also entails bringing back a rich Group object that implements the currently provided Group interface as a domain entity in order to centralize business logic used for Group manipulation, e.g. adding/removing players.

**Comment by siege918** [comment]
I'm definitely for this. Definitely allows faster development, and keeps us from being too married to one back end.
